version: "3.7"
services:
  web:
    container_name: linebot-web
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "127.0.0.1:80:80"
    restart: always

  app:
    container_name: linebot-app
    image: springboot:latest
    build: ./docker/app
    expose:
      - "8080"
    restart: always
    #    command: java -jar -Dspring.profiles.active=docker build/libs/linebot-0.0.1-SNAPSHOT.jar
    command: ./gradlew bootRun
    depends_on:
      - web
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      LINE_BOT_CHANNEL_SECRET: ${LINE_BOT_CHANNEL_SECRET}
      LINE_BOT_CHANNEL_TOKEN: ${LINE_BOT_CHANNEL_TOKEN}

  db:
    container_name: linebot-postgres
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    #    volumes:
    #      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: linebot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    user: root
    restart: always

  pgadmin4:
    container_name: linebot-pgadmin4
    image: dpage/pgadmin4:latest
    ports:
      - 8000:80
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always