version: "3.7"
services:
  web:
    container_name: linebot-web
    build:
      context: ./docker/centos/web
    image: centos-web
    ports:
      - "127.0.0.1:80:80"
    restart: always
    privileged: true
    depends_on:
      - app

  app:
    container_name: linebot-app
    image: springboot:latest
    expose:
      - "8080"
    restart: always
    command: ./gradlew b    ootRun
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      LINE_BOT_CHANNEL_SECRET: ${LINE_BOT_CHANNEL_SECRET}
      LINE_BOT_CHANNEL_TOKEN: ${LINE_BOT_CHANNEL_TOKEN}

  db:
    container_name: linebot-postgres
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    #    volumes:
    #      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: linebot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    user: root
    restart: always

  pgadmin4:
    container_name: linebot-pgadmin4
    image: dpage/pgadmin4:latest
    ports:
      - 8000:80
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always