version: "3.7"
services:
  web:
    container_name: linebot-web
    image: nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    restart: always

  app:
    container_name: linebot-app
    image: openjdk
    volumes:
      - .:/app
    working_dir: /app
    expose:
      - "8080"
    restart: always
    command: ./gradlew bootRun
    depends_on:
      - web
      - db
#    command: >
#      bash -c
#      "git clone https://github.com/Ryoma0622/line-bot.git
#       && cd line-bot
#       && ./gradlew --full-stacktrace -q build
#       && ./gradlew bootRun"

  db:
    container_name: linebot-postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: linebot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    user: root
    restart: always

  pgadmin4:
    container_name: linebot-pgadmin4
    image: dpage/pgadmin4:4.9
    ports:
      - 8000:80
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always