---
all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: linebot-web1
        web02:
          ansible_host: linebot-web2
        web03:
          ansible_host: linebot-web3
  vars:
    web: linebot-web
    app: linebot-app
    db: linebot-db