---
- name: Set repo file
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    mode: 0644

- name: Install nginx
  yum: name={{ item.name }} state={{ item.state }}
  loop:
    - { name: '*', state: 'latest' }
    - { name: 'nginx', state: 'latest' }

- name: Systemd enable service nginx
  service:
    name: nginx
    enabled: yes

- name: Copy innner conf file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d
  notify:
    -  restart nginx